######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 24 20:36:04 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gui.cpp
